# https://docs.aws.amazon.com/waf/latest/APIReference/API_RegexPatternSetReferenceStatement.html
policy:
  - name: "WebACL01"
    description: ~
    scope: "REGIONAL"
    default_action: "block"
    rule:
      name: "RegexPatternRule01"
      priority: 10
      action: "count"
      regex_pattern_set_reference_statement:
        field_to_match:
          single_header:
            name: "host"
        arn: ""
        text_transformation:
          priority: 10
          type: "NONE"
      visibility_config:
        cloudwatch_metrics_enabled: false
        metric_name: "cloudwatch_metric_name"
        sampled_requests_enabled: false
    visibility_config:
      cloudwatch_metrics_enabled: false
      metric_name: "cloudwatch_metric_name1"
      sampled_requests_enabled: false
    tags:
      Team: Security
      Owner: Security