# https://docs.aws.amazon.com/waf/latest/APIReference/API_GeoMatchStatement.html
policy:
  - name: "WebACL01"
    description: ~
    scope: "REGIONAL"
    default_action: "block"
    rule:
      name: "AndStatementRule01"
      priority: 10
      action: "count"
      and_statement:
        statements:
          - geo_match_statement:
              country_codes: ["CN"]
          - geo_match_statement:
              country_codes: ["JP"]
      visibility_config:
        cloudwatch_metrics_enabled: false
        metric_name: "cloudwatch_metric_name"
        sampled_requests_enabled: false
    visibility_config:
      cloudwatch_metrics_enabled: false
      metric_name: "cloudwatch_metric_name1"
      sampled_requests_enabled: false
    tags:
      Team: Security
      Owner: Security

  - name: "WebACL02"
    description: ~
    scope: "REGIONAL"
    default_action: "allow"
    rule:
      name: "AndStatementRule02"
      priority: 10
      action: "block"
      geo_match_statement:
        country_codes: ["JP", "US"]
      visibility_config:
        cloudwatch_metrics_enabled: false
        metric_name: "cloudwatch_metric_name"
        sampled_requests_enabled: false
    visibility_config:
      cloudwatch_metrics_enabled: false
      metric_name: "cloudwatch_metric_name1"
      sampled_requests_enabled: false
    tags:
      Team: Security
