# https://docs.aws.amazon.com/waf/latest/APIReference/API_ManagedRuleGroupStatement.html
policy:
  - name: "WebACL01"
    description: ~
    scope: "REGIONAL"
    default_action: "block"
    rule:
      name: "ManagedRuleGroupRule01"
      priority: 10
      override_action: "count"
      managed_rule_group_statement:
        name: "AWSManagedRulesCommonRuleSet"
        vendor_name: "AWS"
        # Deprecated - excluded_rule: ["NoUserAgent_HEADER", "UserAgent_BadBots_HEADER"]
        rule_action_override:
          block: "NoUserAgent_HEADER"
          count: "UserAgent_BadBots_HEADER"
      visibility_config:
        cloudwatch_metrics_enabled: false
        metric_name: "cloudwatch_metric_name"
        sampled_requests_enabled: false
    visibility_config:
      cloudwatch_metrics_enabled: false
      metric_name: "cloudwatch_metric_name1"
      sampled_requests_enabled: false
    tags:
      Team: Security
      Owner: Security

  - name: "WebACL02"
    description: ~
    scope: "REGIONAL"
    default_action: "allow"
    rule:
      name: "ManagedRuleGroupRule01"
      priority: 10
      override_action: "none"
      managed_rule_group_statement:
        name: "AWSManagedRulesCommonRuleSet"
        vendor_name: "AWS"
        # Deprecated - excluded_rule: ["UserAgent_BadBots_HEADER"]
        rule_action_override:
          count: "UserAgent_BadBots_HEADER"
      visibility_config:
        cloudwatch_metrics_enabled: false
        metric_name: "cloudwatch_metric_name"
        sampled_requests_enabled: false
    visibility_config:
      cloudwatch_metrics_enabled: false
      metric_name: "cloudwatch_metric_name1"
      sampled_requests_enabled: false
    tags:
      Team: Security
