# https://docs.aws.amazon.com/waf/latest/APIReference/API_OrStatement.html
policy:
  - name: "WebACL01"
    description: ~
    scope: "REGIONAL"
    default_action: "block"
    rule:
      name: "OrStatementRule01"
      priority: 10
      action: "count"
      or_statement:
        statements:
          - geo_match_statement:
              country_codes: ["CN"]
          - geo_match_statement:
              country_codes: ["JP"]
      visibility_config:
        cloudwatch_metrics_enabled: false
        metric_name: "cloudwatch_metric_name"
        sampled_requests_enabled: false
    visibility_config:
      cloudwatch_metrics_enabled: false
      metric_name: "cloudwatch_metric_name1"
      sampled_requests_enabled: false
    tags:
      Team: Security
      Owner: Security

  - name: "WebACL02"
    description: ~
    scope: "REGIONAL"
    default_action: "allow"
    rule:
      name: "OrStatementRule02"
      priority: 10
      action: "block"
      or_statement:
        statements:
          - geo_match_statement:
              country_codes: ["JP", "US"]
          - byte_match_statement:
              field_to_match:
                uri_path: { }
              positional_constraint: "CONTAINS"
              search_string: "/test"
              text_transformation:
                priority: 20
                type: "URL_DECODE"
      visibility_config:
        cloudwatch_metrics_enabled: false
        metric_name: "cloudwatch_metric_name"
        sampled_requests_enabled: false
    visibility_config:
      cloudwatch_metrics_enabled: false
      metric_name: "cloudwatch_metric_name1"
      sampled_requests_enabled: false
    tags:
      Team: Security
      Owner: Security
