# https://docs.aws.amazon.com/waf/latest/APIReference/API_AssociateWebACL.html
policy:
  # Resource names can be identified through annotations.
  # ex. alb-name-01 <-> wafv2-webacl-name-01
  - resource_arn: ""
    web_acl_arn: ""
  - resource_arn: ""
    web_acl_arn: ""
