# https://docs.aws.amazon.com/waf/latest/APIReference/API_SizeConstraintStatement.html
policy:
  - name: "WebACL01"
    description: ~
    scope: "REGIONAL"
    default_action: "block"
    rule:
      name: "SizeConstraintRule01"
      priority: 10
      action: "count"
      size_constraint_statement:
        field_to_match:
          method: {}
        comparison_operator: "EQ"
        size: 3
        text_transformation:
          priority: 10
          type: "NONE"
      visibility_config:
        cloudwatch_metrics_enabled: false
        metric_name: "cloudwatch_metric_name"
        sampled_requests_enabled: false
    visibility_config:
      cloudwatch_metrics_enabled: false
      metric_name: "cloudwatch_metric_name1"
      sampled_requests_enabled: false
    tags:
      Team: Security
      Owner: Security