# https://docs.aws.amazon.com/waf/latest/APIReference/API_RateBasedStatement.html
policy:
  - name: "WebACL01"
    description: ~
    scope: "REGIONAL"
    default_action: "block"
    rule:
      name: "RateBasedRule01"
      priority: 10
      action: "count"
      rate_based_statement:
        limit: 1000
        aggregate_key_type: "FORWARDED_IP"
        forwarded_ip_config:
          fallback_behavior: "MATCH"
          header_name: "X-Forwarded-For"
      visibility_config:
        cloudwatch_metrics_enabled: false
        metric_name: "cloudwatch_metric_name"
        sampled_requests_enabled: false
    visibility_config:
      cloudwatch_metrics_enabled: false
      metric_name: "cloudwatch_metric_name1"
      sampled_requests_enabled: false
    tags:
      Team: Security
      Owner: Security