# https://docs.aws.amazon.com/waf/latest/APIReference/API_XssMatchStatement.html
policy:
  - name: "WebACL01"
    description: ~
    scope: "REGIONAL"
    default_action: "block"
    rule:
      name: "XssMatchRule01"
      priority: 10
      action: "count"
      xss_match_statement:
        field_to_match:
          uri_path: {}
        text_transformation:
          priority: 10
          type: "URL_DECODE"
      visibility_config:
        cloudwatch_metrics_enabled: false
        metric_name: "cloudwatch_metric_name"
        sampled_requests_enabled: false
    visibility_config:
      cloudwatch_metrics_enabled: false
      metric_name: "cloudwatch_metric_name1"
      sampled_requests_enabled: false
    tags:
      Team: Security
      Owner: Security